---
name: build
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  call-workflow-test:
    # name: call-workflow-test
    # runs-on: ubuntu-20.04
    # container:
    #   image: ixxel/cd-toolbox:latest
    # steps:
    # - name: first step
    uses: ixxeL-actions/workflows/.github/workflows/container-img-builder.yaml@main
    with:
      workingdir: .
      format: cli
      img-name: test
      artefact: Dockerfile
      tag: v1
      github-api-auth: false
    # name: Build
    # runs-on: ubuntu-20.04
    # container:
    #   image: ixxel/cd-toolbox:latest
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: docker.io/ixxel/ci-toolbox:latest
    #     format: table
    #     vuln-type: os,library
    #     severity: CRITICAL,HIGH
    #   env:
    #     TRIVY_USERNAME: ixxel
    #     TRIVY_PASSWORD: 2794d8ea-0fa5-4039-8036-9bc85f3765af
    # - name: Security scan for docker image (Grype)
    #   id: scan-image1
    #   uses: ixxeL-actions/grype-scan@main
    #   with:
    #     image-ref: docker.io/ixxel/ci-toolbox:latest
    #     transport: registry
    #     fail-on: '""'
    #     output: table
    #     scope: AllLayers
    #     template: '""'
    #     verbose: ''
